export default {
  metadata: {
  "colorSchemeName": "Web light",
  "colorSchemeId": "hig-light",
  "className": "hig--light-theme",
  "densityId": "high-density",
  "densityName": "High density",
  "name": "Web light, High density",
  "fileName": "webLightHighDensityTheme",
  "id": "hig-light-high-density",
  "__deprecated__": {
      "basics.colors.error": {
          "equivalent": "colorScheme.errorColor"
      },
      "basics.colors.success": {
          "equivalent": "colorScheme.successColor"
      },
      "basics.colors.warning": {
          "equivalent": "colorScheme.warningColor"
      }
  }
},
  resolvedRoles: {
  "basics.borderRadii.none": "0",
  "basics.borderRadii.small": "0",
  "basics.borderRadii.medium": "2px",
  "basics.borderRadii.large": "4px",
  "basics.borderRadii.ellipse": "50%",
  "basics.borderRadii.pill": "1000em",
  "basics.borderWidths.none": "0",
  "basics.borderWidths.small": "1px",
  "basics.borderWidths.medium": "2px",
  "basics.borderWidths.large": "4px",
  "basics.colors.black": "#000000",
  "basics.colors.white": "#ffffff",
  "basics.colors.autodeskBlue100": "#cdeaf7",
  "basics.colors.autodeskBlue200": "#9bd5ef",
  "basics.colors.autodeskBlue300": "#6ac0e7",
  "basics.colors.autodeskBlue400": "#38abdf",
  "basics.colors.autodeskBlue500": "#0696d7",
  "basics.colors.autodeskBlue600": "#0686c2",
  "basics.colors.autodeskBlue700": "#0571a1",
  "basics.colors.autodeskBlue800": "#034b6c",
  "basics.colors.autodeskBlue900": "#022c40",
  "basics.colors.charcoal100": "#eeeeee",
  "basics.colors.charcoal200": "#dcdcdc",
  "basics.colors.charcoal300": "#cccccc",
  "basics.colors.charcoal400": "#bbbbbb",
  "basics.colors.charcoal500": "#999999",
  "basics.colors.charcoal600": "#808080",
  "basics.colors.charcoal700": "#666666",
  "basics.colors.charcoal800": "#4d4d4d",
  "basics.colors.charcoal900": "#3c3c3c",
  "basics.colors.darkBlue100": "#e1ebf7",
  "basics.colors.darkBlue200": "#d1deee",
  "basics.colors.darkBlue300": "#a3bcdc",
  "basics.colors.darkBlue400": "#749bcb",
  "basics.colors.darkBlue500": "#4679b9",
  "basics.colors.darkBlue600": "#1858a8",
  "basics.colors.darkBlue700": "#12437f",
  "basics.colors.darkBlue800": "#0e3666",
  "basics.colors.darkBlue900": "#0c2c54",
  "basics.colors.green100": "#e7f2d9",
  "basics.colors.green200": "#cfe4b3",
  "basics.colors.green300": "#b7d78c",
  "basics.colors.green400": "#9fc966",
  "basics.colors.green500": "#87b340",
  "basics.colors.green600": "#658d30",
  "basics.colors.green700": "#5d822c",
  "basics.colors.green800": "#4c6b24",
  "basics.colors.green900": "#445e20",
  "basics.colors.iconLightGrayColor": "#808080",
  "basics.colors.iconDarkBlueColor": "#d1deee",
  "basics.colors.iconDarkGrayColor": "#cccccc",
  "basics.colors.red100": "#ffd9d9",
  "basics.colors.red200": "#f8d3d3",
  "basics.colors.red300": "#f1a7a7",
  "basics.colors.red400": "#eb7a7a",
  "basics.colors.red500": "#ec4a41",
  "basics.colors.red600": "#dd2222",
  "basics.colors.red700": "#a61a1a",
  "basics.colors.red800": "#6f1111",
  "basics.colors.red900": "#630f0f",
  "basics.colors.turquoise100": "#d6f2ef",
  "basics.colors.turquoise200": "#ade4de",
  "basics.colors.turquoise300": "#84d7ce",
  "basics.colors.turquoise400": "#5bc9bd",
  "basics.colors.turquoise500": "#32bcad",
  "basics.colors.turquoise600": "#23a597",
  "basics.colors.turquoise700": "#268d82",
  "basics.colors.turquoise800": "#20756c",
  "basics.colors.turquoise900": "#195e57",
  "basics.colors.yellowOrange100": "#feecd1",
  "basics.colors.yellowOrange200": "#fddaa4",
  "basics.colors.yellowOrange300": "#fcc776",
  "basics.colors.yellowOrange400": "#fbb549",
  "basics.colors.yellowOrange500": "#faa21b",
  "basics.colors.yellowOrange600": "#bb7a14",
  "basics.colors.yellowOrange700": "#916010",
  "basics.colors.yellowOrange800": "#7d510e",
  "basics.colors.yellowOrange900": "#523609",
  "basics.colors.pink100": "#ffebf5",
  "basics.colors.pink200": "#ffd6eb",
  "basics.colors.pink300": "#ffb8db",
  "basics.colors.pink400": "#ff8cc6",
  "basics.colors.pink500": "#fc56a9",
  "basics.colors.pink600": "#e84396",
  "basics.colors.pink700": "#c72877",
  "basics.colors.pink800": "#991f5c",
  "basics.colors.pink900": "#781848",
  "basics.colors.purple100": "#f4edfd",
  "basics.colors.purple200": "#eadcfd",
  "basics.colors.purple300": "#d5bcf7",
  "basics.colors.purple400": "#c5a1f8",
  "basics.colors.purple500": "#b385f2",
  "basics.colors.purple600": "#a76ef5",
  "basics.colors.purple700": "#8558c5",
  "basics.colors.purple800": "#5f3e8e",
  "basics.colors.purple900": "#482f6b",
  "basics.colors.salmon100": "#ffefec",
  "basics.colors.salmon200": "#fcded9",
  "basics.colors.salmon300": "#ffbeb3",
  "basics.colors.salmon400": "#ff9582",
  "basics.colors.salmon500": "#f26a52",
  "basics.colors.salmon600": "#db5942",
  "basics.colors.salmon700": "#a84a39",
  "basics.colors.salmon800": "#853729",
  "basics.colors.salmon900": "#66251a",
  "basics.colors.slate100": "#e9f0f7",
  "basics.colors.slate200": "#dce7f3",
  "basics.colors.slate300": "#c1cedc",
  "basics.colors.slate400": "#a7bacf",
  "basics.colors.slate500": "#7993b0",
  "basics.colors.slate600": "#6784a6",
  "basics.colors.slate700": "#4b6b8f",
  "basics.colors.slate800": "#354d67",
  "basics.colors.slate900": "#2c3e53",
  "basics.colors.surfaceDarkBlueLevel100": "#454f61",
  "basics.colors.surfaceDarkBlueLevel200": "#3b4453",
  "basics.colors.surfaceDarkBlueLevel250": "#2e3440",
  "basics.colors.surfaceDarkBlueLevel300": "#222933",
  "basics.colors.surfaceDarkBlueLevel350": "#1a1f25",
  "basics.colors.surfaceDarkBlueShadow": "rgba(26, 31, 38, 0.5)",
  "basics.colors.surfaceDarkGrayLevel100": "#535353",
  "basics.colors.surfaceDarkGrayLevel200": "#474747",
  "basics.colors.surfaceDarkGrayLevel250": "#373737",
  "basics.colors.surfaceDarkGrayLevel300": "#2a2a2a",
  "basics.colors.surfaceDarkGrayLevel350": "#202020",
  "basics.colors.surfaceDarkGrayShadow": "rgba(0, 0, 0, 0.3)",
  "basics.colors.surfaceLightGrayLevel100": "#ffffff",
  "basics.colors.surfaceLightGrayLevel200": "#f5f5f5",
  "basics.colors.surfaceLightGrayLevel250": "#eeeeee",
  "basics.colors.surfaceLightGrayLevel300": "#d9d9d9",
  "basics.colors.surfaceLightGrayLevel350": "#cccccc",
  "basics.colors.surfaceLightGrayShadow": "rgba(0, 0, 0, 0.2)",
  "basics.colors.textAgainstDark": "#f5f5f5",
  "basics.colors.textAgainstLight": "#3c3c3c",
  "basics.colors.error": "#ec4a41",
  "basics.colors.success": "#87b340",
  "basics.colors.warning": "#faa21b",
  "basics.colors.textLinkAgainstLight": "#006EAF",
  "basics.colors.textLinkAgainstDark": "#6DD2FF",
  "basics.fontFamilies.main": "ArtifaktElement, sans-serif",
  "basics.fontFamilies.monospace": "'Source Code Pro', monospace",
  "basics.fontSizes.highSmall": "11px",
  "basics.fontSizes.highMedium": "12px",
  "basics.fontSizes.highLarge": "16px",
  "basics.fontSizes.highExtraLarge": "20px",
  "basics.fontSizes.highExtraExtraLarge": "24px",
  "basics.fontSizes.mediumSmall": "12px",
  "basics.fontSizes.mediumMedium": "14px",
  "basics.fontSizes.mediumLarge": "20px",
  "basics.fontSizes.mediumExtraLarge": "24px",
  "basics.fontSizes.mediumExtraExtraLarge": "28px",
  "basics.fontSizes.lowSmall": "14px",
  "basics.fontSizes.lowMedium": "16px",
  "basics.fontSizes.lowLarge": "22px",
  "basics.fontSizes.lowExtraLarge": "26px",
  "basics.fontSizes.lowExtraExtraLarge": "30px",
  "basics.fontWeights.regular": 400,
  "basics.fontWeights.medium": 600,
  "basics.fontWeights.bold": 700,
  "basics.lineHeights.small": "1.3",
  "basics.lineHeights.medium": "1.4",
  "basics.lineHeights.large": "1.5",
  "basics.lineHeights.highSmall": "1.25",
  "basics.lineHeights.highMedium": "1.272727273",
  "basics.lineHeights.highLarge": "1.3",
  "basics.lineHeights.highExtraLarge": "1.333333333",
  "basics.lineHeights.highExtraExtraLarge": "1.375",
  "basics.lineHeights.mediumSmall": "1.25",
  "basics.lineHeights.mediumMedium": "1.285714286",
  "basics.lineHeights.mediumLarge": "1.3",
  "basics.lineHeights.mediumExtraLarge": "1.428571429",
  "basics.lineHeights.mediumExtraExtraLarge": "1.5",
  "basics.shadows.lowBlur": "4px",
  "basics.shadows.highBlur": "16px",
  "basics.spacings.none": "0",
  "basics.spacings.highExtraExtraSmall": "2px",
  "basics.spacings.highExtraSmall": "4px",
  "basics.spacings.highSmall": "8px",
  "basics.spacings.highMedium": "12px",
  "basics.spacings.highLarge": "16px",
  "basics.spacings.highExtraLarge": "24px",
  "basics.spacings.highExtraExtraLarge": "32px",
  "basics.spacings.mediumExtraExtraSmall": "4px",
  "basics.spacings.mediumExtraSmall": "8px",
  "basics.spacings.mediumSmall": "12px",
  "basics.spacings.mediumMedium": "16px",
  "basics.spacings.mediumLarge": "24px",
  "basics.spacings.mediumExtraLarge": "32px",
  "basics.spacings.mediumExtraExtraLarge": "48px",
  "basics.spacings.lowExtraExtraSmall": "8px",
  "basics.spacings.lowExtraSmall": "12px",
  "basics.spacings.lowSmall": "16px",
  "basics.spacings.lowMedium": "24px",
  "basics.spacings.lowLarge": "32px",
  "basics.spacings.lowExtraLarge": "48px",
  "basics.spacings.lowExtraExtraLarge": "64px",
  "colorScheme.accentColor": "#0696d7",
  "colorScheme.baseColor": "#808080",
  "colorScheme.highShadowColor": "rgba(0, 0, 0, 0.25)",
  "colorScheme.iconColor": "#808080",
  "colorScheme.lowShadowColor": "rgba(0, 0, 0, 0.25)",
  "colorScheme.surfaceLevel100Color": "#ffffff",
  "colorScheme.surfaceLevel200Color": "#f5f5f5",
  "colorScheme.surfaceLevel250Color": "#eeeeee",
  "colorScheme.surfaceLevel300Color": "#d9d9d9",
  "colorScheme.surfaceLevel350Color": "#cccccc",
  "colorScheme.component.backgroundColor": "#ffffff",
  "colorScheme.textColor": "#3c3c3c",
  "colorScheme.textColorDim": "rgba(60, 60, 60, 0.7)",
  "colorScheme.infoColor": "#38abdf",
  "colorScheme.errorColor": "#ec4a41",
  "colorScheme.successColor": "#87b340",
  "colorScheme.warningColor": "#faa21b",
  "density.spacings.extraExtraSmall": "2px",
  "density.spacings.extraSmall": "4px",
  "density.spacings.small": "8px",
  "density.spacings.medium": "12px",
  "density.spacings.large": "16px",
  "density.spacings.extraLarge": "24px",
  "density.spacings.extraExtraLarge": "32px",
  "density.fontSizes.small": "11px",
  "density.fontSizes.medium": "12px",
  "density.fontSizes.large": "16px",
  "density.fontSizes.extraLarge": "20px",
  "density.fontSizes.extraExtraLarge": "24px",
  "avatar.fontWeight": 400,
  "avatar.fontColorOnDark": "#ffffff",
  "avatar.fontColorOnLight": "#3c3c3c",
  "avatar.extraSmall.fontSize": "11px",
  "avatar.extraSmall.diameter": "16px",
  "avatar.small.fontSize": "12px",
  "avatar.small.diameter": "24px",
  "avatar.medium.fontSize": "14px",
  "avatar.medium.diameter": "32px",
  "avatar.large.fontSize": "24px",
  "avatar.large.diameter": "48px",
  "avatar.extraLarge.fontSize": "30px",
  "avatar.extraLarge.diameter": "64px",
  "avatar.color1.backgroundColor": "#6ac0e7",
  "avatar.color1.fontColor": "#3c3c3c",
  "avatar.color2.backgroundColor": "#1858a8",
  "avatar.color2.fontColor": "#ffffff",
  "avatar.color3.backgroundColor": "#5d822c",
  "avatar.color3.fontColor": "#ffffff",
  "avatar.color4.backgroundColor": "#ff9582",
  "avatar.color4.fontColor": "#3c3c3c",
  "avatar.color5.backgroundColor": "#7993b0",
  "avatar.color5.fontColor": "#ffffff",
  "avatar.color6.backgroundColor": "#5bc9bd",
  "avatar.color6.fontColor": "#3c3c3c",
  "avatar.color7.backgroundColor": "#faa21b",
  "avatar.color7.fontColor": "#3c3c3c",
  "banner.info.iconBackground": "#38abdf",
  "banner.info.borderColor": "rgba(56, 171, 223, 0.5)",
  "banner.info.backgroundColor": "rgba(56, 171, 223, 0.1)",
  "banner.error.iconBackground": "#ec4a41",
  "banner.error.borderColor": "rgba(236, 74, 65, 0.5)",
  "banner.error.backgroundColor": "rgba(236, 74, 65, 0.1)",
  "banner.success.iconBackground": "#87b340",
  "banner.success.borderColor": "rgba(135, 179, 64, 0.5)",
  "banner.success.backgroundColor": "rgba(135, 179, 64, 0.1)",
  "banner.warning.iconBackground": "#faa21b",
  "banner.warning.borderColor": "rgba(250, 162, 27, 0.5)",
  "banner.warning.backgroundColor": "rgba(250, 162, 27, 0.1)",
  "button.borderRadius": "4px",
  "button.borderWidth": "1px",
  "button.fontWeight": 700,
  "button.lineHeight": "14px",
  "button.fontFamily": "ArtifaktElement, sans-serif",
  "button.fontSize": "12px",
  "button.gutter": "4px",
  "button.horizontalPadding": "12px",
  "button.minimumWidth": "10px",
  "button.verticalPadding": "4px",
  "button.halo.width": 0,
  "button.halo.color": "#808080",
  "button.hover.halo.width": "2px",
  "button.hover.halo.color": "rgba(128, 128, 128, 0.15)",
  "button.focus.halo.width": "2px",
  "button.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "button.pressed.halo.width": "4px",
  "button.pressed.halo.color": "rgba(128, 128, 128, 0.25)",
  "button.outline.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.outline.borderColor": "rgb(190, 200, 210)",
  "button.outline.halo.color": "#bbbbbb",
  "button.outline.textColor": "#000000",
  "button.outline.icon.color": "#000000",
  "button.outline.hover.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.outline.hover.borderColor": "#0ED3BE",
  "button.outline.hover.halo.color": "rgba(128, 128, 128, 0.15)",
  "button.outline.hover.textColor": "#000000",
  "button.outline.hover.icon.color": "#000000",
  "button.outline.focus.backgroundColor": "#5CE1D3",
  "button.outline.focus.borderColor": "#5CE1D3",
  "button.outline.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "button.outline.focus.textColor": "#ffffff",
  "button.outline.focus.icon.color": "#ffffff",
  "button.outline.pressed.haloWidth": "4px",
  "button.outline.pressed.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.outline.pressed.borderColor": "#5CE1D3",
  "button.outline.pressed.halo.color": "rgba(255, 255, 255, 0)",
  "button.outline.pressed.textColor": "#000000",
  "button.outline.pressed.icon.color": "#000000",
  "button.solid.backgroundColor": "#0696d7",
  "button.solid.borderColor": "#0696d7",
  "button.solid.halo.color": "#808080",
  "button.solid.textColor": "#ffffff",
  "button.solid.icon.color": "#f5f5f5",
  "button.solid.hover.backgroundColor": "#66BFE9",
  "button.solid.hover.borderColor": "#0696d7",
  "button.solid.hover.halo.color": "rgba(255, 255, 255, 0)",
  "button.solid.hover.textColor": "#ffffff",
  "button.solid.hover.icon.color": "#f5f5f5",
  "button.solid.focus.backgroundColor": "#0671A1",
  "button.solid.focus.borderColor": "#0696d7",
  "button.solid.focus.halo.color": "rgba(255, 255, 255, 0)",
  "button.solid.focus.textColor": "#ffffff",
  "button.solid.focus.icon.color": "#f5f5f5",
  "button.solid.pressed.haloWidth": "4px",
  "button.solid.pressed.backgroundColor": "#0696d7",
  "button.solid.pressed.borderColor": "#0696d7",
  "button.solid.pressed.halo.color": "rgba(255, 255, 255, 0)",
  "button.solid.pressed.textColor": "#ffffff",
  "button.solid.pressed.icon.color": "#f5f5f5",
  "button.flat.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.flat.borderColor": "rgba(255, 255, 255, 0)",
  "button.flat.halo.color": "#808080",
  "button.flat.textColor": "#000000",
  "button.flat.icon.color": "#000000",
  "button.flat.hover.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.flat.hover.borderColor": "#0ED3BE",
  "button.flat.hover.halo.color": "rgba(128, 128, 128, 0.15)",
  "button.flat.hover.textColor": "#000000",
  "button.flat.hover.icon.color": "#000000",
  "button.flat.focus.backgroundColor": "#5CE1D3",
  "button.flat.focus.borderColor": "#5CE1D3",
  "button.flat.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "button.flat.focus.textColor": "#ffffff",
  "button.flat.focus.icon.color": "#ffffff",
  "button.flat.pressed.haloWidth": "4px",
  "button.flat.pressed.backgroundColor": "rgba(255, 255, 255, 0)",
  "button.flat.pressed.borderColor": "rgba(255, 255, 255, 0)",
  "button.flat.pressed.halo.color": "rgba(255, 255, 255, 0)",
  "button.flat.pressed.textColor": "#000000",
  "button.flat.pressed.icon.color": "#000000",
  "checkbox.backgroundColor": "#ffffff",
  "checkbox.borderColor": "rgba(190, 200, 210, 0.5)",
  "checkbox.borderWidth": "1px",
  "checkbox.borderRadius": "3px",
  "checkbox.halo.color": "rgba(128, 128, 128, 0.15)",
  "checkbox.halo.width": "2px",
  "checkbox.height": "12px",
  "checkbox.iconColor": "#ffffff",
  "checkbox.width": "12px",
  "checkbox.hover.borderColor": "rgba(128, 128, 128, 0.5)",
  "checkbox.hover.halo.width": 0,
  "checkbox.hover.halo.color": "rgba(128, 128, 128, 0.15)",
  "checkbox.focus.borderColor": "rgb(6, 113, 161)",
  "checkbox.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "checkbox.focus.halo.width": 0,
  "checkbox.pressed.borderColor": "rgba(128, 128, 128, 0.5)",
  "checkbox.pressed.halo.color": "rgba(128, 128, 128, 0.25)",
  "checkbox.pressed.halo.width": 0,
  "checkbox.checked.borderColor": "#7993B0",
  "checkbox.checked.iconColor": "#ffffff",
  "checkbox.checked.backgroundColor": "#7993B0",
  "checkbox.indeterminate.borderColor": "#7993B0",
  "checkbox.indeterminate.iconColor": "#ffffff",
  "checkbox.indeterminate.backgroundColor": "#7993B0",
  "checkbox.focus.checked.backgroundColor": "#0671A1",
  "checkbox.focus.checked.borderColor": "rgba(6, 113, 161, 0.5)",
  "checkbox.focus.indeterminate.borderColor": "rgba(6, 113, 161, 0.5)",
  "component.disabled.opacity": "0.4",
  "divider.width": "1px",
  "divider.lightColor": "rgba(60, 60, 60, 0.1)",
  "divider.heavyColor": "rgba(60, 60, 60, 0.25)",
  "flyout.backgroundColor": "#ffffff",
  "flyout.borderColor": "#D4DBE1",
  "flyout.borderRadius": "4px",
  "flyout.shadowBlur": "16px",
  "flyout.shadowColor": "rgba(0, 0, 0, 0.25)",
  "flyout.nub.hypotenuseLength": "16px",
  "formField.instructionalText.fontSize": "11px",
  "formField.instructionalText.fontWeight": 400,
  "formField.instructionalText.fontFamily": "ArtifaktElement, sans-serif",
  "formField.instructionalText.fontColor": "rgba(60, 60, 60, 0.6)",
  "formField.instructionalText.lineHeight": "1.4",
  "formField.icon.width": "24px",
  "formField.icon.paddingRight": "8px",
  "formField.icon.color": "#3c3c3c",
  "iconButton.iconColor": "#3B4454",
  "iconButton.on.iconColor": "#0696d7",
  "iconButton.borderRadius": "4px",
  "iconButton.hover.iconColor": "#0ED3BE",
  "iconButton.hover.on.iconColor": "#0571a1",
  "iconButton.focus.iconColor": "#7993B0",
  "iconButton.focus.on.iconColor": "#0696d7",
  "iconButton.focus.halo.color": "rgba(6, 150, 215, 0)",
  "iconButton.focus.halo.width": "2px",
  "iconButton.pressed.iconColor": "#7993B0",
  "iconButton.pressed.on.iconColor": "#0571a1",
  "iconButton.pressed.backgroundColor": "rgba(128, 128, 128, 0)",
  "iconButton.pressed.level100To250.backgroundColor": "rgba(128, 128, 128, 0)",
  "iconButton.pressed.level300To350.backgroundColor": "rgba(255, 255, 255, 0.5)",
  "input.horizontalPadding": "0",
  "input.boxType.horizontalPadding": "8px",
  "input.verticalPadding": "4px",
  "input.borderRadius": "0",
  "input.borderColor": "rgba(128, 128, 128, 0.2)",
  "input.borderWidth": "1px",
  "input.borderBottomColor": "rgba(128, 128, 128, 0.35)",
  "input.borderBottomWidth": "1px",
  "input.fontColor": "#3c3c3c",
  "input.fontWeight": 600,
  "input.fontFamily": "ArtifaktElement, sans-serif",
  "input.fontSize": "12px",
  "input.height": "24px",
  "input.lineHeight": "1.4",
  "input.halo.color": "rgba(14, 211, 190, 0.15)",
  "input.halo.width": "0",
  "input.gutterWidth": "4px",
  "input.placeholder.fontColor": "rgba(60, 60, 60, 0.4)",
  "input.highlightColor": "rgba(6, 150, 215, 0.25)",
  "input.hover.borderBottomColor": "#0ED3BE",
  "input.hover.halo.width": "1px",
  "input.focus.borderBottomColor": "#0696d7",
  "input.focus.halo.width": "1px",
  "input.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "input.active.halo.width": "1px",
  "input.active.halo.color": "rgba(6, 150, 215, 0.25)",
  "input.disabled.opacity": 0.5,
  "input.box.borderBottomColor": "rgba(128, 128, 128, 0.2)",
  "input.box.backgroundColor": "#ffffff",
  "label.fontSize": "12px",
  "label.top.fontSize": "12px",
  "label.fontWeight": 400,
  "label.fontFamily": "ArtifaktElement, sans-serif",
  "label.fontColor": "rgba(60, 60, 60, 0.6)",
  "label.lineHeight": "1.4",
  "label.hover.fontColor": "rgba(60, 60, 60, 0.6)",
  "menu.backgroundColor": "#ffffff",
  "menu.borderRadius": "0",
  "menu.topFlushBorderTopRadius": "0",
  "menu.item.backgroundColor": "#ffffff",
  "menu.item.hover.backgroundColor": "rgb(230, 244, 251)",
  "menu.item.focus.backgroundColor": "rgb(230, 244, 251)",
  "menu.item.active.backgroundColor": "rgb(230, 244, 251)",
  "menu.item.horizontalPadding": "4px",
  "menu.item.verticalPadding": "12px",
  "menu.item.minHeight": "16px",
  "menu.item.gutterWidth": "12px",
  "modal.overlay.color": "rgba(0, 0, 0, 0.5)",
  "modal.textColor": "#2c3e53",
  "modal.body.height": "98px",
  "modal.horizontalPadding": "16px",
  "modal.header.backgroundColor": "#E6F4FB",
  "modal.header.borderColor": "rgba(60, 60, 60, 0.25)",
  "modal.header.height": "45px",
  "modal.window.backgroundColor": "#ffffff",
  "modal.window.borderRadius": "4px",
  "modal.window.height": "200px",
  "modal.window.width": "400px",
  "modal.window.shadowColor": "#BEC8D2",
  "progressBar.backgroundColor": "rgb(236, 240, 243)",
  "progressBar.highlightColor": "#0ED3BE",
  "progressBar.borderRadius": "2px",
  "progressBar.height": "4px",
  "progressRing.backgroundColor": "rgba(0, 0, 0, 0.05)",
  "progressRing.highlightColor1": "rgb(14, 211, 190)",
  "progressRing.highlightColor2": "rgb(12, 168, 153)",
  "skeletonItem.borderRadius": "2px",
  "skeletonItem.defaultHeight": "12px",
  "skeletonItem.backgroundColor": "rgba(0, 0, 0, 0.06)",
  "skeletonItem.highlightColor": "rgba(255, 255, 255, 0.3)",
  "slider.halo.width": "2px",
  "slider.halo.color": "#ffffff",
  "slider.thumb.backgroundColor": "#D4DBE1",
  "slider.thumb.width": "9px",
  "slider.track.color": "rgba(212, 219, 225, 0.2)",
  "slider.track.width": "1px",
  "slider.value.color": "#D4DBE1",
  "slider.focused.halo.color": "rgb(255, 255, 255)",
  "slider.focused.halo.width": "2px",
  "slider.focused.thumb.color": "#0696D7",
  "slider.hover.halo.color": "rgb(255, 255, 255)",
  "slider.hover.halo.width": "2px",
  "slider.hover.thumb.color": "#0ED3BE",
  "slider.pressed.halo.color": "rgb(255, 255, 255)",
  "slider.pressed.halo.width": "4px",
  "slider.pressed.thumb.color": "#0671A1",
  "tabs.general.borderBottomColor": "rgba(128, 128, 128, 0.1)",
  "tabs.general.borderBottomWidth": "1px",
  "tabs.general.gutter": "4px",
  "tabs.general.tab.fontFamily": "ArtifaktElement, sans-serif",
  "tabs.general.tab.fontSize": "16px",
  "tabs.general.tab.fontWeight": 400,
  "tabs.general.tab.selected.borderBottomColor": "#0696d7",
  "tabs.general.tab.selected.borderBottomWidth": "2px",
  "tabs.general.tab.selected.fontWeight": 700,
  "tabs.general.tab.disabled.fontColor": "rgba(60, 60, 60, 0.5)",
  "tabs.general.tab.hover.borderBottomColor": "rgba(128, 128, 128, 0.5)",
  "tabs.general.tab.hover.borderBottomWidth": "2px",
  "tabs.general.tab.focus.halo.color": "rgba(6, 150, 215, 0.5)",
  "tabs.general.tab.focus.halo.width": "4px",
  "textArea.minHeight": "250px",
  "textArea.borderColor": "rgba(128, 128, 128, 0.2)",
  "textLink.textColor": "#0696D7",
  "textLink.hover.textColor": "#0671A1",
  "textLink.focus.textColor": "#024B6C",
  "textLink.hover.underline.color": "transparent",
  "textLink.focus.halo.color": "rgba(6, 150, 215, 0.35)",
  "textLink.focus.halo.width": "0",
  "tooltip.backgroundColor": "#393939",
  "tooltip.borderColor": "#393939",
  "tooltip.borderRadius": "4px",
  "tooltip.shadowBlur": "16px",
  "tooltip.shadowColor": "rgba(0, 0, 0, 0.25)",
  "tooltip.textColor": "#ffffff",
  "tooltip.nub.hypotenuseLength": "16px",
  "typography.body.fontFamily": "ArtifaktElement, sans-serif",
  "typography.body.fontWeight": 400,
  "typography.body.fontSize": "12px",
  "typography.body.lineHeight": "1.333333333",
  "typography.body.color": "#3c3c3c",
  "typography.caption.fontFamily": "ArtifaktElement, sans-serif",
  "typography.caption.fontWeight": 400,
  "typography.caption.fontSize": "11px",
  "typography.caption.lineHeight": "1.272727273",
  "typography.caption.color": "#3c3c3c",
  "typography.h1.fontFamily": "ArtifaktElement, sans-serif",
  "typography.h1.fontWeight": 400,
  "typography.h1.fontSize": "24px",
  "typography.h1.lineHeight": "1.25",
  "typography.h1.color": "#3c3c3c",
  "typography.h2.fontFamily": "ArtifaktElement, sans-serif",
  "typography.h2.fontWeight": 400,
  "typography.h2.fontSize": "20px",
  "typography.h2.lineHeight": "1.3",
  "typography.h2.color": "#3c3c3c",
  "typography.h3.fontFamily": "ArtifaktElement, sans-serif",
  "typography.h3.fontWeight": 600,
  "typography.h3.fontSize": "16px",
  "typography.h3.lineHeight": "1.375",
  "typography.h3.color": "#3c3c3c"
},
  props: {
    MuiButtonBase: {
      disableRipple: true
    }
  },
  typography: {
    fontFamily: "ArtifaktElement, sans-serif",
    fontWeightRegular: "400",
    fontWeightMedium: "700",
    useNextVariants: true,
    body1: {
      fontSize: "12px",
      fontWeight: "400",
      lineHeight: "1.4",
      color: "#3c3c3c"
    },
    h1: {
      fontSize: "24px",
      fontWeight: "400",
      lineHeight: "1.3",
      color: "#3c3c3c"
    },
    h2: {
      fontSize: "20px",
      fontWeight: "400",
      lineHeight: "1.285714286",
      color: "#3c3c3c"
    },
    h3: {
      fontSize: "16px",
      fontWeight: "600",
      lineHeight: "1.25",
      color: "#3c3c3c"
    },
    h4: {
      fontSize: "12px",
      fontWeight: "600",
      lineHeight: "1.25",
      color: "#3c3c3c"
    },
    h5: {
      fontSize: "11px",
      fontWeight: "600",
      lineHeight: "1.25",
      color: "#3c3c3c"
    },
    h6: {
      fontSize: "11px",
      fontWeight: "600",
      lineHeight: "1.25",
      color: "#3c3c3c"
    },
    caption: {
      fontSize: "11px",
      lineHeight: "1.272727273",
      color: "#3c3c3c",
      textAlign: "left"
    }
  },
  palette: {
    background: {
      default: "#ffffff",
      paper: "#ffffff"
    },
    primary: {
      main: "#0696d7"
    },
    secondary: {
      main: "#0696d7"
    }
  },
  overrides: {
    MuiButton: {
      root: {
        borderColor: 'transparent',
        borderRadius: "4px",
        borderWidth: "1px",
        fontFamily: "ArtifaktElement, sans-serif",
        fontSize: "12px!important",
        fontWeight: "700",
        lineHeight: "14px",
        minWidth: "10px",
        padding: "4px 12px!important",
        textTransform: 'none',
        marginLeft: "4px",
        marginRight: "4px",
    },
    text: {
      backgroundColor: "rgba(255, 255, 255, 0)",
      borderColor: "rgba(255, 255, 255, 0)",
      color: "#000000",
      "& svg * ": {fill: "#000000"},
      "&:hover": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        borderColor: "#0ED3BE",
        boxShadow: "rgba(128, 128, 128, 0.15) 0 0 0 2px",
        color: "#000000",
        "& svg * ": {
          fill: "#000000"
        },
      },
      "&:focus": {
        backgroundColor: "#5CE1D3",
        borderColor: "#5CE1D3",
        boxShadow: "rgba(6, 150, 215, 0.35) 0 0 0 2px",
        color: "#ffffff",
        "& svg * ": {
          fill: "#ffffff"
        },
      },
      "&:active": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        borderColor: "rgba(255, 255, 255, 0)",
        boxShadow: "rgba(255, 255, 255, 0) 0 0 0 4px!important",
        color: "#000000",
        "& svg * ": {
          fill: "#000000"
        },
      },
      "&$disabled": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        color: "#000000",
        opacity: '0.3',
      }
    },
    outlined: {
      backgroundColor: "rgba(255, 255, 255, 0)",
      borderColor: "rgb(190, 200, 210)",
      color: "#000000",
      "& svg * ": {
        fill: "#000000"
      },
      "&:hover": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        borderColor: "#0ED3BE",
        boxShadow: "rgba(128, 128, 128, 0.15) 0 0 0 2px",
        color: "#000000",
        "& svg * ": {
          fill: "#000000"
        },
      },
      "&:focus": {
        backgroundColor: "#5CE1D3",
        borderColor: "#5CE1D3",
        boxShadow: "rgba(6, 150, 215, 0.35) 0 0 0 2px",
        color: "#ffffff",
        "& svg * ": {
          fill: "#ffffff"
        },
      },
      "&:active": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        borderColor: "#5CE1D3",
        boxShadow: "rgba(255, 255, 255, 0) 0 0 0 4px!important",
        color: "#000000",
        "& svg * ": {
          fill: "#000000"
        },
      },
      "&$disabled": {
        backgroundColor: "rgba(255, 255, 255, 0)",
        borderColor: "rgb(190, 200, 210)",
        color: "#000000",
        opacity: '0.3',
      }
    },
    contained: {
      backgroundColor: "#0696d7",
      borderColor: "#0696d7",
      boxShadow: 'none',
      color: "#ffffff",
      "& svg * ": {
        fill: "#f5f5f5"
      },
      "&:hover": {
        backgroundColor: "#66BFE9",
        borderColor: "#0696d7",
        boxShadow: "rgba(255, 255, 255, 0) 0 0 0 2px",
        color: "#ffffff",
        "& svg * ": {
          fill: "#f5f5f5"
        },
      },
      "&:focus": {
        backgroundColor: "#0671A1",
        borderColor: "#0696d7",
        boxShadow: "rgba(255, 255, 255, 0) 0 0 0 2px",
        color: "#ffffff",
        "& svg * ": {
          fill: "#f5f5f5"
        },
      },
      "&:active": {
        backgroundColor: "#0696d7",
        borderColor: "#0696d7",
        boxShadow: "rgba(255, 255, 255, 0) 0 0 0 4px!important",
        color: "#ffffff",
        "& svg * ": {
          fill: "#f5f5f5"
        },
      },
      "&$disabled": {
        backgroundColor: "#0696d7",
        color: "#ffffff",
        opacity: '0.3',
      }
      }
    }
  }
};
