import React from 'react';
import * as HIGIcons from "@hig/icons";

function App() {
	return (
		<table>
			<tr><td>AddFolder24</td><td><HIGIcons.AddFolder24 /></td></tr>
			<tr><td>AddMember24</td><td><HIGIcons.AddMember24 /></td></tr>
			<tr><td>AddPage24</td><td><HIGIcons.AddPage24 /></td></tr>
			<tr><td>Add24</td><td><HIGIcons.Add24 /></td></tr>
			<tr><td>Alert24</td><td><HIGIcons.Alert24 /></td></tr>
			<tr><td>Archive24</td><td><HIGIcons.Archive24 /></td></tr>
			<tr><td>AreaPost24</td><td><HIGIcons.AreaPost24 /></td></tr>
			<tr><td>Attach24</td><td><HIGIcons.Attach24 /></td></tr>
			<tr><td>Attachment24</td><td><HIGIcons.Attachment24 /></td></tr>
			<tr><td>Back24</td><td><HIGIcons.Back24 /></td></tr>
			<tr><td>BillStack24</td><td><HIGIcons.BillStack24 /></td></tr>
			<tr><td>Billing24</td><td><HIGIcons.Billing24 /></td></tr>
			<tr><td>Bookmark24</td><td><HIGIcons.Bookmark24 /></td></tr>
			<tr><td>Building24</td><td><HIGIcons.Building24 /></td></tr>
			<tr><td>Calendar24</td><td><HIGIcons.Calendar24 /></td></tr>
			<tr><td>CaretDown24</td><td><HIGIcons.CaretDown24 /></td></tr>
			<tr><td>CaretLeft24</td><td><HIGIcons.CaretLeft24 /></td></tr>
			<tr><td>CaretRight24</td><td><HIGIcons.CaretRight24 /></td></tr>
			<tr><td>CaretUp24</td><td><HIGIcons.CaretUp24 /></td></tr>
			<tr><td>CartEmpty24</td><td><HIGIcons.CartEmpty24 /></td></tr>
			<tr><td>CartFull24</td><td><HIGIcons.CartFull24 /></td></tr>
			<tr><td>Chat24</td><td><HIGIcons.Chat24 /></td></tr>
			<tr><td>Checklist24</td><td><HIGIcons.Checklist24 /></td></tr>
			<tr><td>Checkmark24</td><td><HIGIcons.Checkmark24 /></td></tr>
			<tr><td>Clock24</td><td><HIGIcons.Clock24 /></td></tr>
			<tr><td>ClosedCaptioning24</td><td><HIGIcons.ClosedCaptioning24 /></td></tr>
			<tr><td>Cloud24</td><td><HIGIcons.Cloud24 /></td></tr>
			<tr><td>Collaboration24</td><td><HIGIcons.Collaboration24 /></td></tr>
			<tr><td>CollapsePanel24</td><td><HIGIcons.CollapsePanel24 /></td></tr>
			<tr><td>Comment24</td><td><HIGIcons.Comment24 /></td></tr>
			<tr><td>Compare24</td><td><HIGIcons.Compare24 /></td></tr>
			<tr><td>Complete24</td><td><HIGIcons.Complete24 /></td></tr>
			<tr><td>Copy24</td><td><HIGIcons.Copy24 /></td></tr>
			<tr><td>CtaArrowRight24</td><td><HIGIcons.CtaArrowRight24 /></td></tr>
			<tr><td>Dashboard24</td><td><HIGIcons.Dashboard24 /></td></tr>
			<tr><td>DeviceDesktop24</td><td><HIGIcons.DeviceDesktop24 /></td></tr>
			<tr><td>DeviceMobile24</td><td><HIGIcons.DeviceMobile24 /></td></tr>
			<tr><td>DeviceTablet24</td><td><HIGIcons.DeviceTablet24 /></td></tr>
			<tr><td>Devices24</td><td><HIGIcons.Devices24 /></td></tr>
			<tr><td>DocumentManagement24</td><td><HIGIcons.DocumentManagement24 /></td></tr>
			<tr><td>Down24</td><td><HIGIcons.Down24 /></td></tr>
			<tr><td>Download24</td><td><HIGIcons.Download24 /></td></tr>
			<tr><td>Edit24</td><td><HIGIcons.Edit24 /></td></tr>
			<tr><td>Education24</td><td><HIGIcons.Education24 /></td></tr>
			<tr><td>Error24</td><td><HIGIcons.Error24 /></td></tr>
			<tr><td>ExpandPanel24</td><td><HIGIcons.ExpandPanel24 /></td></tr>
			<tr><td>ExportMove24</td><td><HIGIcons.ExportMove24 /></td></tr>
			<tr><td>ExternalLink24</td><td><HIGIcons.ExternalLink24 /></td></tr>
			<tr><td>External24</td><td><HIGIcons.External24 /></td></tr>
			<tr><td>Favorite24</td><td><HIGIcons.Favorite24 /></td></tr>
			<tr><td>Featured24</td><td><HIGIcons.Featured24 /></td></tr>
			<tr><td>Feedback24</td><td><HIGIcons.Feedback24 /></td></tr>
			<tr><td>Field24</td><td><HIGIcons.Field24 /></td></tr>
			<tr><td>FileAssembly24</td><td><HIGIcons.FileAssembly24 /></td></tr>
			<tr><td>FileAudio24</td><td><HIGIcons.FileAudio24 /></td></tr>
			<tr><td>FileDocument24</td><td><HIGIcons.FileDocument24 /></td></tr>
			<tr><td>FileGeneric24</td><td><HIGIcons.FileGeneric24 /></td></tr>
			<tr><td>FileImage24</td><td><HIGIcons.FileImage24 /></td></tr>
			<tr><td>FilePart24</td><td><HIGIcons.FilePart24 /></td></tr>
			<tr><td>FilePdf24</td><td><HIGIcons.FilePdf24 /></td></tr>
			<tr><td>FilePresentation24</td><td><HIGIcons.FilePresentation24 /></td></tr>
			<tr><td>FileSpreadsheet24</td><td><HIGIcons.FileSpreadsheet24 /></td></tr>
			<tr><td>FileVideo24</td><td><HIGIcons.FileVideo24 /></td></tr>
			<tr><td>FileZip24</td><td><HIGIcons.FileZip24 /></td></tr>
			<tr><td>FilterTokens24</td><td><HIGIcons.FilterTokens24 /></td></tr>
			<tr><td>Filter24</td><td><HIGIcons.Filter24 /></td></tr>
			<tr><td>Flag24</td><td><HIGIcons.Flag24 /></td></tr>
			<tr><td>FolderOpen24</td><td><HIGIcons.FolderOpen24 /></td></tr>
			<tr><td>Folder24</td><td><HIGIcons.Folder24 /></td></tr>
			<tr><td>Forums24</td><td><HIGIcons.Forums24 /></td></tr>
			<tr><td>Forward24</td><td><HIGIcons.Forward24 /></td></tr>
			<tr><td>Globe24</td><td><HIGIcons.Globe24 /></td></tr>
			<tr><td>Graph24</td><td><HIGIcons.Graph24 /></td></tr>
			<tr><td>Grid24</td><td><HIGIcons.Grid24 /></td></tr>
			<tr><td>Help24</td><td><HIGIcons.Help24 /></td></tr>
			<tr><td>Hidden24</td><td><HIGIcons.Hidden24 /></td></tr>
			<tr><td>Hierarchy24</td><td><HIGIcons.Hierarchy24 /></td></tr>
			<tr><td>Home24</td><td><HIGIcons.Home24 /></td></tr>
			<tr><td>Import24</td><td><HIGIcons.Import24 /></td></tr>
			<tr><td>Inbox24</td><td><HIGIcons.Inbox24 /></td></tr>
			<tr><td>Info24</td><td><HIGIcons.Info24 /></td></tr>
			<tr><td>Item24</td><td><HIGIcons.Item24 /></td></tr>
			<tr><td>Link24</td><td><HIGIcons.Link24 /></td></tr>
			<tr><td>List24</td><td><HIGIcons.List24 /></td></tr>
			<tr><td>Location24</td><td><HIGIcons.Location24 /></td></tr>
			<tr><td>Lock24</td><td><HIGIcons.Lock24 /></td></tr>
			<tr><td>Mail24</td><td><HIGIcons.Mail24 /></td></tr>
			<tr><td>ManageAccess24</td><td><HIGIcons.ManageAccess24 /></td></tr>
			<tr><td>Maximize24</td><td><HIGIcons.Maximize24 /></td></tr>
			<tr><td>Minimize24</td><td><HIGIcons.Minimize24 /></td></tr>
			<tr><td>MoreVertical24</td><td><HIGIcons.MoreVertical24 /></td></tr>
			<tr><td>More24</td><td><HIGIcons.More24 /></td></tr>
			<tr><td>Mute24</td><td><HIGIcons.Mute24 /></td></tr>
			<tr><td>NotEditable24</td><td><HIGIcons.NotEditable24 /></td></tr>
			<tr><td>Notification24</td><td><HIGIcons.Notification24 /></td></tr>
			<tr><td>OnlineViewers24</td><td><HIGIcons.OnlineViewers24 /></td></tr>
			<tr><td>Paste24</td><td><HIGIcons.Paste24 /></td></tr>
			<tr><td>Pause24</td><td><HIGIcons.Pause24 /></td></tr>
			<tr><td>PermissionGroup24</td><td><HIGIcons.PermissionGroup24 /></td></tr>
			<tr><td>PermissionIndividual24</td><td><HIGIcons.PermissionIndividual24 /></td></tr>
			<tr><td>Photos24</td><td><HIGIcons.Photos24 /></td></tr>
			<tr><td>Pin24</td><td><HIGIcons.Pin24 /></td></tr>
			<tr><td>Placeholder24</td><td><HIGIcons.Placeholder24 /></td></tr>
			<tr><td>Play24</td><td><HIGIcons.Play24 /></td></tr>
			<tr><td>Print24</td><td><HIGIcons.Print24 /></td></tr>
			<tr><td>ProductsAndServices24</td><td><HIGIcons.ProductsAndServices24 /></td></tr>
			<tr><td>Profile24</td><td><HIGIcons.Profile24 /></td></tr>
			<tr><td>ProjectManagement24</td><td><HIGIcons.ProjectManagement24 /></td></tr>
			<tr><td>Properties24</td><td><HIGIcons.Properties24 /></td></tr>
			<tr><td>Publish24</td><td><HIGIcons.Publish24 /></td></tr>
			<tr><td>Quantities24</td><td><HIGIcons.Quantities24 /></td></tr>
			<tr><td>Recommend24</td><td><HIGIcons.Recommend24 /></td></tr>
			<tr><td>Redo24</td><td><HIGIcons.Redo24 /></td></tr>
			<tr><td>Report24</td><td><HIGIcons.Report24 /></td></tr>
			<tr><td>Save24</td><td><HIGIcons.Save24 /></td></tr>
			<tr><td>Search24</td><td><HIGIcons.Search24 /></td></tr>
			<tr><td>Security24</td><td><HIGIcons.Security24 /></td></tr>
			<tr><td>SelectAll24</td><td><HIGIcons.SelectAll24 /></td></tr>
			<tr><td>SelectNone24</td><td><HIGIcons.SelectNone24 /></td></tr>
			<tr><td>Service24</td><td><HIGIcons.Service24 /></td></tr>
			<tr><td>Settings24</td><td><HIGIcons.Settings24 /></td></tr>
			<tr><td>Share24</td><td><HIGIcons.Share24 /></td></tr>
			<tr><td>SocialBlog24</td><td><HIGIcons.SocialBlog24 /></td></tr>
			<tr><td>SocialFacebook24</td><td><HIGIcons.SocialFacebook24 /></td></tr>
			<tr><td>SocialInstagram24</td><td><HIGIcons.SocialInstagram24 /></td></tr>
			<tr><td>SocialLinkedin24</td><td><HIGIcons.SocialLinkedin24 /></td></tr>
			<tr><td>SocialTwitter24</td><td><HIGIcons.SocialTwitter24 /></td></tr>
			<tr><td>SocialYoutube24</td><td><HIGIcons.SocialYoutube24 /></td></tr>
			<tr><td>Sort24</td><td><HIGIcons.Sort24 /></td></tr>
			<tr><td>Subscription24</td><td><HIGIcons.Subscription24 /></td></tr>
			<tr><td>Support24</td><td><HIGIcons.Support24 /></td></tr>
			<tr><td>SurveyEquipment24</td><td><HIGIcons.SurveyEquipment24 /></td></tr>
			<tr><td>Sync24</td><td><HIGIcons.Sync24 /></td></tr>
			<tr><td>Tag24</td><td><HIGIcons.Tag24 /></td></tr>
			<tr><td>Trash24</td><td><HIGIcons.Trash24 /></td></tr>
			<tr><td>Unavailable24</td><td><HIGIcons.Unavailable24 /></td></tr>
			<tr><td>Undo24</td><td><HIGIcons.Undo24 /></td></tr>
			<tr><td>Unlink24</td><td><HIGIcons.Unlink24 /></td></tr>
			<tr><td>Unlock24</td><td><HIGIcons.Unlock24 /></td></tr>
			<tr><td>Unpin24</td><td><HIGIcons.Unpin24 /></td></tr>
			<tr><td>Up24</td><td><HIGIcons.Up24 /></td></tr>
			<tr><td>Upload24</td><td><HIGIcons.Upload24 /></td></tr>
			<tr><td>UserInactive24</td><td><HIGIcons.UserInactive24 /></td></tr>
			<tr><td>Visible24</td><td><HIGIcons.Visible24 /></td></tr>
			<tr><td>Volume24</td><td><HIGIcons.Volume24 /></td></tr>
			<tr><td>ZoomIn24</td><td><HIGIcons.ZoomIn24 /></td></tr>
			<tr><td>ZoomOut24</td><td><HIGIcons.ZoomOut24 /></td></tr>
			<tr><td>AddFolder16</td><td><HIGIcons.AddFolder16 /></td></tr>
			<tr><td>AddMember16</td><td><HIGIcons.AddMember16 /></td></tr>
			<tr><td>AddPage16</td><td><HIGIcons.AddPage16 /></td></tr>
			<tr><td>Add16</td><td><HIGIcons.Add16 /></td></tr>
			<tr><td>Alert16</td><td><HIGIcons.Alert16 /></td></tr>
			<tr><td>Archive16</td><td><HIGIcons.Archive16 /></td></tr>
			<tr><td>AreaPost16</td><td><HIGIcons.AreaPost16 /></td></tr>
			<tr><td>Attach16</td><td><HIGIcons.Attach16 /></td></tr>
			<tr><td>Attachment16</td><td><HIGIcons.Attachment16 /></td></tr>
			<tr><td>Back16</td><td><HIGIcons.Back16 /></td></tr>
			<tr><td>BillStack16</td><td><HIGIcons.BillStack16 /></td></tr>
			<tr><td>Billing16</td><td><HIGIcons.Billing16 /></td></tr>
			<tr><td>Bookmark16</td><td><HIGIcons.Bookmark16 /></td></tr>
			<tr><td>Building16</td><td><HIGIcons.Building16 /></td></tr>
			<tr><td>Calendar16</td><td><HIGIcons.Calendar16 /></td></tr>
			<tr><td>CaretDown16</td><td><HIGIcons.CaretDown16 /></td></tr>
			<tr><td>CaretLeft16</td><td><HIGIcons.CaretLeft16 /></td></tr>
			<tr><td>CaretRight16</td><td><HIGIcons.CaretRight16 /></td></tr>
			<tr><td>CaretUp16</td><td><HIGIcons.CaretUp16 /></td></tr>
			<tr><td>CartEmpty16</td><td><HIGIcons.CartEmpty16 /></td></tr>
			<tr><td>CartFull16</td><td><HIGIcons.CartFull16 /></td></tr>
			<tr><td>Chat16</td><td><HIGIcons.Chat16 /></td></tr>
			<tr><td>Checklist16</td><td><HIGIcons.Checklist16 /></td></tr>
			<tr><td>Checkmark16</td><td><HIGIcons.Checkmark16 /></td></tr>
			<tr><td>Clock16</td><td><HIGIcons.Clock16 /></td></tr>
			<tr><td>ClosedCaptioning16</td><td><HIGIcons.ClosedCaptioning16 /></td></tr>
			<tr><td>Cloud16</td><td><HIGIcons.Cloud16 /></td></tr>
			<tr><td>Collaboration16</td><td><HIGIcons.Collaboration16 /></td></tr>
			<tr><td>CollapsePanel16</td><td><HIGIcons.CollapsePanel16 /></td></tr>
			<tr><td>Comment16</td><td><HIGIcons.Comment16 /></td></tr>
			<tr><td>Compare16</td><td><HIGIcons.Compare16 /></td></tr>
			<tr><td>Complete16</td><td><HIGIcons.Complete16 /></td></tr>
			<tr><td>Copy16</td><td><HIGIcons.Copy16 /></td></tr>
			<tr><td>CtaArrowRight16</td><td><HIGIcons.CtaArrowRight16 /></td></tr>
			<tr><td>Dashboard16</td><td><HIGIcons.Dashboard16 /></td></tr>
			<tr><td>DeviceDesktop16</td><td><HIGIcons.DeviceDesktop16 /></td></tr>
			<tr><td>DeviceMobile16</td><td><HIGIcons.DeviceMobile16 /></td></tr>
			<tr><td>DeviceTablet16</td><td><HIGIcons.DeviceTablet16 /></td></tr>
			<tr><td>Devices16</td><td><HIGIcons.Devices16 /></td></tr>
			<tr><td>DocumentManagement16</td><td><HIGIcons.DocumentManagement16 /></td></tr>
			<tr><td>Down16</td><td><HIGIcons.Down16 /></td></tr>
			<tr><td>Download16</td><td><HIGIcons.Download16 /></td></tr>
			<tr><td>Edit16</td><td><HIGIcons.Edit16 /></td></tr>
			<tr><td>Education16</td><td><HIGIcons.Education16 /></td></tr>
			<tr><td>Error16</td><td><HIGIcons.Error16 /></td></tr>
			<tr><td>ExpandPanel16</td><td><HIGIcons.ExpandPanel16 /></td></tr>
			<tr><td>ExportMove16</td><td><HIGIcons.ExportMove16 /></td></tr>
			<tr><td>ExternalLink16</td><td><HIGIcons.ExternalLink16 /></td></tr>
			<tr><td>External16</td><td><HIGIcons.External16 /></td></tr>
			<tr><td>Favorite16</td><td><HIGIcons.Favorite16 /></td></tr>
			<tr><td>Featured16</td><td><HIGIcons.Featured16 /></td></tr>
			<tr><td>Feedback16</td><td><HIGIcons.Feedback16 /></td></tr>
			<tr><td>Field16</td><td><HIGIcons.Field16 /></td></tr>
			<tr><td>FileAssembly16</td><td><HIGIcons.FileAssembly16 /></td></tr>
			<tr><td>FileAudio16</td><td><HIGIcons.FileAudio16 /></td></tr>
			<tr><td>FileDocument16</td><td><HIGIcons.FileDocument16 /></td></tr>
			<tr><td>FileGeneric16</td><td><HIGIcons.FileGeneric16 /></td></tr>
			<tr><td>FileImage16</td><td><HIGIcons.FileImage16 /></td></tr>
			<tr><td>FilePart16</td><td><HIGIcons.FilePart16 /></td></tr>
			<tr><td>FilePdf16</td><td><HIGIcons.FilePdf16 /></td></tr>
			<tr><td>FilePresentation16</td><td><HIGIcons.FilePresentation16 /></td></tr>
			<tr><td>FileSpreadsheet16</td><td><HIGIcons.FileSpreadsheet16 /></td></tr>
			<tr><td>FileVideo16</td><td><HIGIcons.FileVideo16 /></td></tr>
			<tr><td>FileZip16</td><td><HIGIcons.FileZip16 /></td></tr>
			<tr><td>FilterTokens16</td><td><HIGIcons.FilterTokens16 /></td></tr>
			<tr><td>Filter16</td><td><HIGIcons.Filter16 /></td></tr>
			<tr><td>Flag16</td><td><HIGIcons.Flag16 /></td></tr>
			<tr><td>FolderOpen16</td><td><HIGIcons.FolderOpen16 /></td></tr>
			<tr><td>Folder16</td><td><HIGIcons.Folder16 /></td></tr>
			<tr><td>Forums16</td><td><HIGIcons.Forums16 /></td></tr>
			<tr><td>Forward16</td><td><HIGIcons.Forward16 /></td></tr>
			<tr><td>Globe16</td><td><HIGIcons.Globe16 /></td></tr>
			<tr><td>Graph16</td><td><HIGIcons.Graph16 /></td></tr>
			<tr><td>Grid16</td><td><HIGIcons.Grid16 /></td></tr>
			<tr><td>Help16</td><td><HIGIcons.Help16 /></td></tr>
			<tr><td>Hidden16</td><td><HIGIcons.Hidden16 /></td></tr>
			<tr><td>Hierarchy16</td><td><HIGIcons.Hierarchy16 /></td></tr>
			<tr><td>Home16</td><td><HIGIcons.Home16 /></td></tr>
			<tr><td>Import16</td><td><HIGIcons.Import16 /></td></tr>
			<tr><td>Inbox16</td><td><HIGIcons.Inbox16 /></td></tr>
			<tr><td>Info16</td><td><HIGIcons.Info16 /></td></tr>
			<tr><td>Item16</td><td><HIGIcons.Item16 /></td></tr>
			<tr><td>Link16</td><td><HIGIcons.Link16 /></td></tr>
			<tr><td>List16</td><td><HIGIcons.List16 /></td></tr>
			<tr><td>Location16</td><td><HIGIcons.Location16 /></td></tr>
			<tr><td>Lock16</td><td><HIGIcons.Lock16 /></td></tr>
			<tr><td>Mail16</td><td><HIGIcons.Mail16 /></td></tr>
			<tr><td>ManageAccess16</td><td><HIGIcons.ManageAccess16 /></td></tr>
			<tr><td>Maximize16</td><td><HIGIcons.Maximize16 /></td></tr>
			<tr><td>Minimize16</td><td><HIGIcons.Minimize16 /></td></tr>
			<tr><td>MoreVertical16</td><td><HIGIcons.MoreVertical16 /></td></tr>
			<tr><td>More16</td><td><HIGIcons.More16 /></td></tr>
			<tr><td>Mute16</td><td><HIGIcons.Mute16 /></td></tr>
			<tr><td>NotEditable16</td><td><HIGIcons.NotEditable16 /></td></tr>
			<tr><td>Notification16</td><td><HIGIcons.Notification16 /></td></tr>
			<tr><td>OnlineViewers16</td><td><HIGIcons.OnlineViewers16 /></td></tr>
			<tr><td>Paste16</td><td><HIGIcons.Paste16 /></td></tr>
			<tr><td>Pause16</td><td><HIGIcons.Pause16 /></td></tr>
			<tr><td>PermissionGroup16</td><td><HIGIcons.PermissionGroup16 /></td></tr>
			<tr><td>PermissionIndividual16</td><td><HIGIcons.PermissionIndividual16 /></td></tr>
			<tr><td>Photos16</td><td><HIGIcons.Photos16 /></td></tr>
			<tr><td>Pin16</td><td><HIGIcons.Pin16 /></td></tr>
			<tr><td>Placeholder16</td><td><HIGIcons.Placeholder16 /></td></tr>
			<tr><td>Play16</td><td><HIGIcons.Play16 /></td></tr>
			<tr><td>Print16</td><td><HIGIcons.Print16 /></td></tr>
			<tr><td>ProductsAndServices16</td><td><HIGIcons.ProductsAndServices16 /></td></tr>
			<tr><td>Profile16</td><td><HIGIcons.Profile16 /></td></tr>
			<tr><td>ProjectManagement16</td><td><HIGIcons.ProjectManagement16 /></td></tr>
			<tr><td>Properties16</td><td><HIGIcons.Properties16 /></td></tr>
			<tr><td>Publish16</td><td><HIGIcons.Publish16 /></td></tr>
			<tr><td>Quantities16</td><td><HIGIcons.Quantities16 /></td></tr>
			<tr><td>Recommend16</td><td><HIGIcons.Recommend16 /></td></tr>
			<tr><td>Redo16</td><td><HIGIcons.Redo16 /></td></tr>
			<tr><td>Report16</td><td><HIGIcons.Report16 /></td></tr>
			<tr><td>Save16</td><td><HIGIcons.Save16 /></td></tr>
			<tr><td>Search16</td><td><HIGIcons.Search16 /></td></tr>
			<tr><td>Security16</td><td><HIGIcons.Security16 /></td></tr>
			<tr><td>SelectAll16</td><td><HIGIcons.SelectAll16 /></td></tr>
			<tr><td>SelectNone16</td><td><HIGIcons.SelectNone16 /></td></tr>
			<tr><td>Service16</td><td><HIGIcons.Service16 /></td></tr>
			<tr><td>Settings16</td><td><HIGIcons.Settings16 /></td></tr>
			<tr><td>Share16</td><td><HIGIcons.Share16 /></td></tr>
			<tr><td>SocialBlog16</td><td><HIGIcons.SocialBlog16 /></td></tr>
			<tr><td>SocialFacebook16</td><td><HIGIcons.SocialFacebook16 /></td></tr>
			<tr><td>SocialInstagram16</td><td><HIGIcons.SocialInstagram16 /></td></tr>
			<tr><td>SocialLinkedin16</td><td><HIGIcons.SocialLinkedin16 /></td></tr>
			<tr><td>SocialTwitter16</td><td><HIGIcons.SocialTwitter16 /></td></tr>
			<tr><td>SocialYoutube16</td><td><HIGIcons.SocialYoutube16 /></td></tr>
			<tr><td>Sort16</td><td><HIGIcons.Sort16 /></td></tr>
			<tr><td>Subscription16</td><td><HIGIcons.Subscription16 /></td></tr>
			<tr><td>Support16</td><td><HIGIcons.Support16 /></td></tr>
			<tr><td>SurveyEquipment16</td><td><HIGIcons.SurveyEquipment16 /></td></tr>
			<tr><td>Sync16</td><td><HIGIcons.Sync16 /></td></tr>
			<tr><td>Tag16</td><td><HIGIcons.Tag16 /></td></tr>
			<tr><td>Trash16</td><td><HIGIcons.Trash16 /></td></tr>
			<tr><td>Unavailable16</td><td><HIGIcons.Unavailable16 /></td></tr>
			<tr><td>Undo16</td><td><HIGIcons.Undo16 /></td></tr>
			<tr><td>Unlink16</td><td><HIGIcons.Unlink16 /></td></tr>
			<tr><td>Unlock16</td><td><HIGIcons.Unlock16 /></td></tr>
			<tr><td>Unpin16</td><td><HIGIcons.Unpin16 /></td></tr>
			<tr><td>Up16</td><td><HIGIcons.Up16 /></td></tr>
			<tr><td>Upload16</td><td><HIGIcons.Upload16 /></td></tr>
			<tr><td>UserInactive16</td><td><HIGIcons.UserInactive16 /></td></tr>
			<tr><td>Visible16</td><td><HIGIcons.Visible16 /></td></tr>
			<tr><td>Volume16</td><td><HIGIcons.Volume16 /></td></tr>
			<tr><td>ZoomIn16</td><td><HIGIcons.ZoomIn16 /></td></tr>
			<tr><td>ZoomOut16</td><td><HIGIcons.ZoomOut16 /></td></tr>
			<tr><td>CaretDownMUI</td><td><HIGIcons.CaretDownMUI /></td></tr>
			<tr><td>CaretDownSUI</td><td><HIGIcons.CaretDownSUI /></td></tr>
			<tr><td>CaretDownXsUI</td><td><HIGIcons.CaretDownXsUI /></td></tr>
			<tr><td>CaretLeftMUI</td><td><HIGIcons.CaretLeftMUI /></td></tr>
			<tr><td>CaretLeftSUI</td><td><HIGIcons.CaretLeftSUI /></td></tr>
			<tr><td>CaretLeftXsUI</td><td><HIGIcons.CaretLeftXsUI /></td></tr>
			<tr><td>CaretRightMUI</td><td><HIGIcons.CaretRightMUI /></td></tr>
			<tr><td>CaretRightSUI</td><td><HIGIcons.CaretRightSUI /></td></tr>
			<tr><td>CaretRightXsUI</td><td><HIGIcons.CaretRightXsUI /></td></tr>
			<tr><td>CaretUpMUI</td><td><HIGIcons.CaretUpMUI /></td></tr>
			<tr><td>CaretUpSUI</td><td><HIGIcons.CaretUpSUI /></td></tr>
			<tr><td>CaretUpXsUI</td><td><HIGIcons.CaretUpXsUI /></td></tr>
			<tr><td>CheckmarkSUI</td><td><HIGIcons.CheckmarkSUI /></td></tr>
			<tr><td>CheckmarkXsUI</td><td><HIGIcons.CheckmarkXsUI /></td></tr>
			<tr><td>CloseLUI</td><td><HIGIcons.CloseLUI /></td></tr>
			<tr><td>CloseMUI</td><td><HIGIcons.CloseMUI /></td></tr>
			<tr><td>CloseSUI</td><td><HIGIcons.CloseSUI /></td></tr>
			<tr><td>CloseXsUI</td><td><HIGIcons.CloseXsUI /></td></tr>
			<tr><td>HamburgerCloseUI</td><td><HIGIcons.HamburgerCloseUI /></td></tr>
			<tr><td>HamburgerDefaultUI</td><td><HIGIcons.HamburgerDefaultUI /></td></tr>
			<tr><td>OperatorMinusSUI</td><td><HIGIcons.OperatorMinusSUI /></td></tr>
			<tr><td>OperatorMinusXsUI</td><td><HIGIcons.OperatorMinusXsUI /></td></tr>
			<tr><td>OperatorPlusSUI</td><td><HIGIcons.OperatorPlusSUI /></td></tr>
			<tr><td>OperatorPlusXsUI</td><td><HIGIcons.OperatorPlusXsUI /></td></tr>
		</table>
	);
}


export default App;
